### PR TITLE
[14.0][MIG] l10n_th_withholding_tax_cert_form

### PR DESCRIPTION
**Pull request by Saran440**
Enhance this module
- depend l10n_th_fonts instead of add new font
- change path /static/scss to /static/src/scss (standard odoo)

depends on
- [x] l10n_th_withholding_tax_cert https://github.com/OCA/l10n-thailand/pull/206
- [x] cherry pick - https://github.com/OCA/l10n-thailand/pull/207

### CODE REVIEW

**Comment by kittiu** [comment]
You plan to include this feature https://github.com/OCA/l10n-thailand/pull/207 too?

**Comment by Saran440** [comment]
Yes, I will.

**Review by kittiu — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Pull request merged**
