### PR TITLE
[FIX] l10n_th_amount_to_text - word in config readme file

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Review by newtratip — APPROVED** [review]

**Comment by kittiu** [comment]
@Saran440 you need to rebase to get development_status

**Comment by Saran440** [comment]
@kittiu Fixed. Thank you for your reviewed.

**Review by ps-tubtim — APPROVED** [review]

**Comment by kittiu** [comment]
Looks like this is ocabot problem. https://travis-ci.com/github/OCA/l10n-thailand/jobs/444171374
It is the same as this https://github.com/OCA/l10n-thailand/pull/188

@sbidoul sorry to nag you. Are we during maintainer tools change? Do I need to do anything for this repo.

**Comment by kittiu** [comment]
Manual merge due to travis problem.

**Pull request merged**
