### PR TITLE
[13.0][ADD] l10n_th_partner : swap text fields for Individual case

### PR DESCRIPTION
**Pull request by poonlap**
l10n_th_partner has a feature which separates an individual name to "First name" and "Last name". But the current input form for "Individual" starts with "Last name", then follow by "First name". Apparently, Thais will expect "First name" first. 

From my experience of this module first testing, I didn't notice the label "Last name", and I just typed the first name in that text field.

image

This PR proposes swapping these text fields to the order of "first name" first, follow by "last name".

image

### CODE REVIEW

**Comment by Saran440** [comment]
Functional Test :+1: 
@poonlap  Could you squash your commits?

**Comment by poonlap** [comment]
@Saran440  I donlt know how to handle squashing, and I think now I messed up my local repo. May I just close this PR and start over?

**Comment by Saran440** [comment]
@poonlap Step to squash commits:
Go to folder l10n-thailand and used
`git rebase -i origin/13.0` (origin is repo OCA)

Selection_006
you will see all your commits (2 commits) and change `pick` to `s` or `squash`, than save and comment commit that you don't need
Selection_007
next save and used
`git push -f`

ref : https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by poonlap** [comment]
@Saran440  Thank you for the advise. I'm still not sure what I have done. Let's see. At least, I can see only one commit.

**Comment by Saran440** [comment]
Okay, it's not work. I can't direct rebase this PR. there are 2 ways to fix.
1. open new pr 1 commit.
2. study and used squash your commit. (this way useful for other pr) :)

**Comment by poonlap** [comment]
@Saran440 I will create the new PR.

**Pull request closed without merging**
