### PR TITLE
[16.0][MIG] l10n_th_fonts: Migration to 16.0

### PR DESCRIPTION
**Pull request by amincheloh**

### CODE REVIEW

**Comment by Saran440** [comment]
@amincheloh
please update your code again.
we fix error pre-commit here https://github.com/OCA/l10n-thailand/pull/320

thank you :)

**Comment by amincheloh** [comment]
@Saran440 updated

**Review by ps-tubtim — APPROVED** [review]
LGTM.

**Review by Saran440 — APPROVED** [review]
Code not changed :+1:

**Pull request merged**
