### PR TITLE
[14.0][MIG] l10n_th_fonts: Migration to 14.0

### PR DESCRIPTION
**Pull request by newtratip**
Ready for review

### CODE REVIEW

**Comment by Saran440** [comment]
Functional Test. LGTM. :+1: 

But I have to plan change feature in this module 

**Concept**
this module should be collects all font thai only
if other module would like to used thai font, it will depend this module and select font manual

**Example**
10 module (1 module / 1 form) use thai font. 3 module need `TH Sarabun`, 7 module need `Angsana new`
1 module will depends this and choose font manually.  WDYT?

**Comment by newtratip** [comment]
@Saran440 Good idea, I think module name is `l10n_th_base_fonts` WDYT ?

**Comment by newtratip** [comment]
If OK, I will create new module and let you know for reviewing.

**Comment by newtratip** [comment]
@kittiu WDYT about @Saran440 commented.

**Comment by kittiu** [comment]
> WIP

@newtratip this is still WIP? Please change the comment above if it is ready. I can merge soon.

**Comment by newtratip** [comment]
I will add feature as @Saran440 commented later if I have a time. Thank you for fast merging :)

**Comment by kittiu** [comment]
Rebased.

**Pull request merged**
