### PR TITLE
[13.0][MIG] l10n_th_withholding_tax_report

### PR DESCRIPTION
**Pull request by kongrattapong**
### Work in progress
========================
* [x] PDF report
* [x] HTML report
* [ ] XLSX report - waiting module [report_xlsx_helper](https://github.com/OCA/reporting-engine/pull/361) migration to V13
* [ ] TXT report - waiting module [report_csv](https://github.com/OCA/reporting-engine/pull/367) migration to V13

### CODE REVIEW

**Comment by kittiu** [comment]
@kongrattapong before I move on with the review. I think, to generate TXT file, we should use report_csv instead of xlsx_import_export. This is to make things more inline (qweb, xlsx, txt to use same technique).

Can you,
* Migrate this to v13 -> https://github.com/OCA/reporting-engine/tree/12.0/report_csv
* Change this module to use report_csv.

Thanks!

**Comment by kongrattapong** [comment]
@kittiu Sorry for late reply.
Migrate report_csv : https://github.com/OCA/reporting-engine/pull/367
and I adjust code to use that module already.

thank for your review.

**Comment by kittiu** [comment]
Please rebase

**Comment by kongrattapong** [comment]
rebase already.

**Comment by kittiu** [comment]
@kongrattapong, we can continue this case, only report_csv left, we will try to push it up.

**Comment by kittiu** [comment]
@kongrattapong all modules needed are merged. Can you rebase please?
I can do more review and move this forward.

**Comment by newtratip** [comment]
@kongrattapong Please fix conflicting file, check CI and update your description (report_xlsx_helper, report_csv is merged)

I will help review after you are done this.

**Pull request merged**
