### PR TITLE
[16.0][MIG] l10n_th_account_wht_cert_form

### PR DESCRIPTION
**Pull request by Saran440**
No code changed.

Depend On:
- [x] https://github.com/OCA/l10n-thailand/pull/394

### CODE REVIEW

**Comment by supichayat** [comment]
Tested about printing **Withholding Tax Certificate Form**
there are some errors found as attached below
unknown_085

**Comment by Saran440** [comment]
@supichayat Fixed. Can you recheck again, please?

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
