### PR TITLE
[13.0][FIX] l10n_th_withholding_tax_cert_form : domain groupby wt_lines

### PR DESCRIPTION
**Pull request by Saran440**
Error print cert if document > 1, it will print all document into 1 form

Selection_001
Selection_002

### CODE REVIEW

**Comment by newtratip** [comment]
@Saran440 Could you fix CI red ? May be pre-commit.

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Comment by kittiu** [comment]
@ps-tubtim please update this to your proj.

**Pull request merged**
