### PR TITLE
[13.0][FIX] l10n_th_withholding_tax_cert_form - Improved code

### PR DESCRIPTION
**Pull request by Saran440**
- Change menu name to `WT Certificates (pdf)`
- Fix readme file
- Depend `l10n_th_amount_to_text` instead new function
- Add background 'ยกเลิก' in Form when WT Cert state 'cancel'
- Update type of WT Cert
- Add 'แทนที่เอกสาร old WT Cert' when WT Cert is instead of old WT Cert
- Move on code to correct folder
- Add Test script
- Group by wt lines when type is same as.

depend on https://github.com/OCA/l10n-thailand/pull/171

### CODE REVIEW

**Comment by Cncd10** [comment]
Functional Review @Saran440 

WT Certificates (PDF)
เอกสารที่ถูกยกเลิก (SUPP.OUT/2020/0021) แล้วมีเอกสารใบใหม่ (MISC/2020/0011 (SUPP.OUT/2020/0021))
ใบเก่า(Status = Cancelled) ควรแสดง "ยกเลิก"
Selection_112
ใบใหม่(Status = Done)  
Selection_113

**Comment by Saran440** [comment]
- Add background 'ยกเลิก' when WT Cert state 'cancel'
- Update type of WT Cert
- Add 'แทนที่เอกสาร old WT Cert' when WT Cert is instead of old WT Cert
- Move on code to correct folder

**Comment by Saran440** [comment]
@Cncd10 Fixed. Could you review again please?

**Review by ps-tubtim — APPROVED** [review]
Code: OK. Functional Test: OK.

Selection_127

**Review by Cncd10 — APPROVED** [review]
@Saran440  
Functional Approve :100:

**Comment by Saran440** [comment]
@kittiu Could you merge?

**Comment by Saran440** [comment]
Fixed
- group by wt lines when type is same as.
- Improved code qweb is good.

**Pull request merged**
