### PR TITLE
[15.0][ADD] l10n_th_gov_hr_expense

### PR DESCRIPTION
**Pull request by ps-tubtim**
This module adds the following features to Expense Report document, aimed to follow Thai Government regulations.

1. Add the Purchase Type field to Expense
2. Allow linking the Purchase Request to Expense Report
3. Allow general users can edit Taxes and Bill Reference

Waiting for

- [x] https://github.com/OCA/l10n-thailand/pull/333
- [x] https://github.com/OCA/hr-expense/pull/177

### CODE REVIEW

**Review by supichayat — APPROVED** [review]
functional tested

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Review by Saran440 — CHANGES_REQUESTED** [review]
This module depend on
- [x] hr_expense_advance_overdue_reminder - https://github.com/OCA/hr-expense/pull/182

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
