### PR TITLE
Update __manifest__.py

### PR DESCRIPTION
**Pull request by sansirit**
To handle external python packages.
So, no need for 'pip install requests'

### CODE REVIEW

**Comment by kittiu** [comment]
Thank you for your contribution. Seem like travis still red with error on pre-commit.
May be the good idea is to `pre-commit run -a` first at your local.
More about pre-commit,
https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

**Review by sansirit — COMMENTED** [review]
there is a missing comma "," at the end of line 15

**Comment by newtratip** [comment]
@sansirit This module is required for library python `requests` ? I don't see to import in python file.

**Comment by kittiu** [comment]
I guess we don't need this. Let me know if we need to reopen.

**Pull request closed without merging**
