### PR TITLE
[12.0][FIX] l10n_th_vat_report

### PR DESCRIPTION
**Pull request by ps-tubtim**
[FIX] render xlsx report (because of https://github.com/OCA/reporting-engine/pull/364)

### CODE REVIEW

**Comment by Saran440** [comment]
@ps-tubtim please, Using `cherry-pick` from PR #102  instead of hard code to make sure this PR will not conflict file

**Review by Saran440 — APPROVED** [review]

**Comment by kittiu** [comment]
@ps-tubtim if you done with this, can this pass on to 13.0 ?

**Comment by ps-tubtim** [comment]
@kittiu I will edit this code manually on 13.0 because module's name changed(l10n_th_vat_report -> l10n_th_tax_report). Can I do this?

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
Yes please do it @ps-tubtim

**Pull request merged**
