### PR TITLE
[13.0][IMP] l10n_th_tax_report, doc ref to always use invoice

### PR DESCRIPTION
**Pull request by kittiu**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The merge bot is restored for working, so you can relaunch, but it would advisable to have at least one reviewer.

**Comment by kittiu** [comment]
> advisable

Thanks @pedrobaeza

**Comment by kittiu** [comment]
@Saran440 or @ps-tubtim can you help please?

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
