### PR TITLE
[ADD] l10n_th_expense_tax_invoice

### PR DESCRIPTION
**Pull request by kittiu**
This module make sure that Expense will also comply with Tax Invoice concept of l10n_th_tax_invoice.

In case expense has VAT,

* Expense's Bill Reference and Date will be used as Tax Invoice Number and Tax Invoice Date
* Without Bill Reference, Post Journal Entry is not allowed

### CODE REVIEW

**Comment by kittiu** [comment]
@Saran440 @ps-tubtim @newtratip 
Please help in review.

**Review by ps-tubtim — COMMENTED** [review]
Code LGTM. Functional Test Ok. Please check the license and copyright.

**Comment by kittiu** [comment]
@ps-tubtim what do you mean by license and copyright? We had it.

**Comment by Saran440** [comment]
@kittiu I think Copyright should be 2020 and init file not necessary to add Copyright.

**Comment by kittiu** [comment]
> @kittiu I think Copyright should be 2020 and init file not necessary to add Copyright.

Done

**Review by Saran440 — APPROVED** [review]
Functional Test. LGTM :+1:

Could you fix red travis?

**Pull request merged**
