### PR TITLE
[12.0][FIX] Report - Tax Amount

### PR DESCRIPTION
**Pull request by kongrattapong**
Issue: https://github.com/OCA/l10n-thailand/issues/96

Selection_075
Selection_076

### CODE REVIEW

**Comment by kittiu** [comment]
I think what I mean is if th result was -10.0 the report should show +10.0 in report

In other words, it should show as abs(amount)

Is this fix correct?

**Comment by kongrattapong** [comment]
> I think what I mean is if th result was -10.0 the report should show +10.0 in report
> 
> In other words, it should show as abs(amount)
> 
> Is this fix correct?

oh, I thought minus values is not correct, I get it now I'll fixed it

**Comment by kongrattapong** [comment]
Fix as the same https://github.com/OCA/l10n-thailand/pull/101
Selection_098


HTML
Selection_095


PDF
Selection_096


XLSX
Selection_097

**Comment by kongrattapong** [comment]
Fix as the same https://github.com/OCA/l10n-thailand/pull/101
Selection_098


HTML
Selection_095


PDF
Selection_096


XLSX
Selection_097

**Review by Saran440 — APPROVED** [review]
Code reviewed. LGTM :+1:

**Review by kittiu — APPROVED** [review]

**Pull request merged**
