### PR TITLE
[13.0][FIX] test script UserError import not thai

### PR DESCRIPTION
**Pull request by Saran440**
Fix test script error :(

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
Still dead -> https://travis-ci.org/github/OCA/l10n-thailand/jobs/733318036#L966

**Comment by Saran440** [comment]
@kittiu okay, this dead becase sometime UserError sometime NOT.
I fixed it by try exception.

**Review by newtratip — APPROVED** [review]

**Pull request merged**
