### PR TITLE
[12.0][FIX] l10n_th_withholding_tax_report : Sort header column

### PR DESCRIPTION
**Pull request by newtratip**
cc : @Saran440

### CODE REVIEW

**Review by Saran440 — CHANGES_REQUESTED** [review]
please cherry-pick
https://github.com/OCA/l10n-thailand/pull/142
https://github.com/OCA/l10n-thailand/pull/159
https://github.com/OCA/l10n-thailand/pull/173

thank you.

**Comment by kittiu** [comment]
Red Travis. development_status, should be Capital letter now, i.e., "Alpha", "Beta".

**Comment by kittiu** [comment]
@newtratip can you cherry pick as Saran suggested? And try pushing again please.

Also, why you need this change? And also in v13 too?

**Comment by kittiu** [comment]
@newtratip this is ready?

**Comment by newtratip** [comment]
> @newtratip this is ready?

This PR is fixed for sort column header, it's ready to merge.

For @Saran440 https://github.com/OCA/l10n-thailand/pull/194#pullrequestreview-523247143, I will cherry pick on another PR.

Thank !

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
