### PR TITLE
[15.0][MIG] l10n_th_promptpay

### PR DESCRIPTION
**Pull request by kurogeek**

### CODE REVIEW

**Comment by kittiu** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by kurogeek** [comment]
@kittiu thanks for the advice, this is done.

**Comment by kittiu** [comment]
Please resolve conflict, other than that it is good to go.

**Review by kittiu — APPROVED** [review]

**Comment by kurogeek** [comment]
Should be good now.

**Comment by kittiu** [comment]
@Saran440 can you review please.

**Comment by Saran440** [comment]
No major change LGTM :+1:

@kurogeek Cloud you rebase this PR into 2 commit?
- [IMP] $MODULE: black, isort, prettier
- [MIG] $MODULE: Migration to 15.0

**Comment by kurogeek** [comment]
@Saran440 I just did please check. However the commit "Merge branch '15.0' into 15.0-mig-l10n_th_promptpay" is inevitable. Because it would have a conflict if I did not include this commit.

**Comment by kurogeek** [comment]
> No major change LGTM 👍
> 
> @kurogeek Cloud you rebase this PR into 2 commit?
> 
>     * [IMP] $MODULE: black, isort, prettier
> 
>     * [MIG] $MODULE: Migration to 15.0

@Saran440 I found the way to do it, it's done. Thanks.

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
