### PR TITLE
[16.0][ADD] l10n_th_account_payment_register_order

### PR DESCRIPTION
**Pull request by kittiu**
By standard Odoo, from an invoice, user make payment by click on Register Payment which
launch a Payment Wizard.

This module change Payment Register Wizard which was `models.TransientModel`
into a permanent menu Payment Register `models.Model`

The way the payment works is still the same as before, but it gives extra benefits,

* By being a new stored documents, it now has states Draft/Paid/Cancel
* It is now possible to extend the document further, i.e., approval process.
* When payment is paid, this document keep tracks of reconciled invoices vs payments
* It is no possible to cancel the Payment Register (and set the payment to draft), and reconcile it back later

Configuration
=============

To use the new persistent payment register document, go to Invoice Settings.

* Use Persistent Document on Inbound Payment - for Customer Invoices
* Use Persistent Document on Outbound Payment - for Vendor Bills

image

image

### CODE REVIEW

**Comment by kittiu** [comment]
Usage example,

Create 2 invoices 100 USD, both has withholding tax 3 USD

image

Click Register Payment, now the Payment Register wizard become a new document by itself.

1. Amount auto deducted as usual = 200 - 6 = 194 USD
2. As Withholding Tax = 6 USD

image

User can chang, amount, change to multi deduct and add another deduct

image

Create Payment (1 payment). It is also possible to cancel it (payment will be set to draft and reconciled from invoices)

image

Re-reconcile the same invoice and payment again.

image

**Review by Nantikan23 — COMMENTED** [review]
Tested and I found some issue as below,
In case that user chose a wrong journal in payment and need to change it after created payment
the system not allow to change them after cancel the permanent and go back to edit journal in the payment document in draft state, the error shown as attached

Screenshot from 2024-03-20 15-32-27

**Comment by kittiu** [comment]
I think it is normal, because the Journal Entry is already created, and it won't allow changing Journal. @Nantikan23 
The point is, the Journal Number is also ran. So I think we shouldn't change Journal.

**Comment by Saran440** [comment]
Change this PR following:
- change name module from `l10n_th_account_payment_register_perm` to `l10n_th_account_payment_register_order`
- add name in form view payment.register.order
- change invoice(s) and payment(s) from `many2many_tags` to `many2many` (Support if many invoice(s))
Selection_022

**Pull request closed without merging**
