### PR TITLE
[13.0][ADD] l10n_th_address [WIP]

### PR DESCRIPTION
**Pull request by kiattipong**

### CODE REVIEW

**Comment by kittiu** [comment]
Some initial comments (I will full review later),
* You should add description that explain briefly what this module is doing. It is good for reviewer.
* Change title to [13.0][ADD] l10n_th_address [WIP]
  * Note: you can end it as WIP to let people know that it is not ready for review.
* Have you use pre-commit ?
  * https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97
  * In short, do following in the working folder, it will auto fix some of your code.
```
> pip install pre-commit
> pre-commit run -a
```
* Add readme folder (see sample from other addons or https://github.com/OCA/mis-builder/tree/13.0/mis_builder/readme
  * Note: README.rst will be auto generated by combining all files after it get merged.
* Later on, please add some unit test (as usual, see sample from other addons)

**Comment by kiattipong** [comment]
Thank you for the review

**Comment by kiattipong** [comment]
Screen Shot 2563-01-31 at 09 43 35
I got the module dependencies error from Travis

**Comment by kittiu** [comment]
@kiattipong พอดีว่ายังไม่ได้ใส่ไฟล์ oca_dependencies.txt ใน 13.0 ตอนนี้ใส่แล้วครับ ให้เอ็ม rebase code จาก 13.0 oca เข้า branch ของเอ็ม
ถ้ายังไม่เคย rebase ลองหาอ่าน concept ดูนะ ปกติพี่ทำแบบนี้
> cd my-working-v13-branch
> git fetch upstream 13.0    # upstream = OCA
> git rebase upstream/13.0

**Comment by kiattipong** [comment]
thank you krub

**Comment by kittiu** [comment]
@kiattipong do you still want to continue with this krub?

**Pull request closed without merging**
