### PR TITLE
[16.0][MIG] l10n_th_amount_to_text

### PR DESCRIPTION
**Pull request by Saran440**
In core odoo change num2words to version 0.5.9 https://github.com/odoo/odoo/blob/16.0/requirements.txt#L27
So, it's now support thai language (0.5.7+)

This PR fixed test script to support new version

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
LGTM.

**Review by Nantikan23 — APPROVED** [review]
Functional Tested

**Pull request merged**
