### PR TITLE
[FIX] tax report, to show negative for refund

### PR DESCRIPTION
**Pull request by kittiu**

### CODE REVIEW

**Comment by kittiu** [comment]
cc @ps-tubtim

**Review by Saran440 — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]

**Comment by ps-tubtim** [comment]
Please fix this in xlsx file.

https://github.com/ecosoft-odoo/l10n-thailand/blob/bd5c5f61b8bddbccec5327beff5d0e8c53162d6b/l10n_th_tax_report/reports/tax_report_xlsx.py#L129

https://github.com/ecosoft-odoo/l10n-thailand/blob/bd5c5f61b8bddbccec5327beff5d0e8c53162d6b/l10n_th_tax_report/reports/tax_report_xlsx.py#L143

**Pull request merged**
