### PR TITLE
[14.0][ADD] l10n_th_company_novat_cosmetic

### PR DESCRIPTION
**Pull request by kittiu**
**For company with normal VAT registered**

Selection_195

**For company with No-VAT registered, but Vendor is VAT.**

The price unit entered is untaxed, i.e., 500 x 2 lines.

1. For VAT vendor, default % VAT is shown
2. Use helper to calculate Included Tax price unit, and the cosmetic price unit and subtotal before vat.
3. Showing cosmetic price unit and subtotal before vat.

Selection_193

**As the result**

Selection_194

### CODE REVIEW

**Comment by kittiu** [comment]
@flook-chaiwat @newtratip

**Comment by kittiu** [comment]
This is still needed.

**Review by ps-tubtim — APPROVED** [review]
Code and functional test: ok.

**Comment by kittiu** [comment]
@Saran440 @newtratip can you help final approve this?

**Review by newtratip — APPROVED** [review]

**Pull request closed without merging**
