### PR TITLE
[15.0][ADD] l10n_th_gov_account_asset_management

### PR DESCRIPTION
**Pull request by ps-tubtim**
This module adds the following features to asset management, aimed to follow Thai Government regulations.

1. Asset Start Date from Accepted Date (if any)
2. Add the Removed Reason field
3. Add a feature to remove multi assets at the same time

Waiting for

- [x] https://github.com/OCA/l10n-thailand/pull/328
- [x] https://github.com/OCA/account-financial-tools/pull/1528
- [x] https://github.com/OCA/purchase-workflow/pull/1555

### CODE REVIEW

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Review by Saran440 — APPROVED** [review]
Code review :+1:

**Pull request merged**
