### PR TITLE
[15.0][FIX] l10n_th_account_tax: tax_base compute following move lines

### PR DESCRIPTION
**Pull request by Saran440**
Change field `tax_base_amount` and `balance` in `tax invoice` to compute field

Fix bug from https://github.com/OCA/l10n-thailand/issues/313

@kittiu What do you think?

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]

**Comment by ps-tubtim** [comment]
@Saran440 Please rebase your commit and rename it by adding the module's name.

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Pull request merged**
