### PR TITLE
[12.0][ADD] l10n_th_vendor_tax_invoice

### PR DESCRIPTION
**Pull request by kittiu**
This module address the undue tax requirement for Thailand

In Odoo, cash basis feature is being used to cover case of undue tax (due on payment).
This can answer the issue about undue tax in Thailand partially.
For customer invoice/payment, Odoo's cash basis alone is enough.

But for supplier invoice/payment, where tax invoice number and tax date is given from vendor.
This module will provide ways for user to do so on vendor bill (for normal tax) and
in supplier payment (for undue tax which is due on payment).

### CODE REVIEW

**Comment by kittiu** [comment]
@OCA/community-maintainers it seem that ci/runbot filed here, and showing only 404: Page not found!
Anything we can do?

**Comment by kittiu** [comment]
@pedrobaeza can you help please?

**Comment by pedrobaeza** [comment]
I have been able to login in http://3369258-17-ea7fe5.runbot2-2.odoo-community.org

The red status is due to warnings, but logs are not reachable, possibly because we changed some things in runbot servers. I have launched a rebuild of the instance to see.

Please tell me again if not reachable yet when finished.

**Comment by kittiu** [comment]
> I have been able to login in http://3369258-17-ea7fe5.runbot2-2.odoo-community.org
> 
> The red status is due to warnings, but logs are not reachable, possibly because we changed some things in runbot servers. I have launched a rebuild of the instance to see.
> 
> Please tell me again if not reachable yet when finished.

@pedrobaeza yes, it does not work. I even try to push some change.

**Comment by pedrobaeza** [comment]
@gurneyalex can you please check why runbot logs are not accessible? I see this in several builds across repositories

**Comment by kittiu** [comment]
Merged as beta

**Comment by newtratip** [comment]
Hi @kittiu 

For Customer's Undue Tax, date should be payment date ?

**Pull request merged**
