### PR TITLE
[15.0][FIX] l10n_th_multicurrency_revaluation: amount on journal entry is not correct if create currency revaluation with partial payment on the invoice

### PR DESCRIPTION
**Pull request by newtratip**
**Step to error**

1. On 01/01/2024, a vendor bill was issued for 100 CNY at a rate of 1 CNY = 5 THB.
2. A payment of 40 CNY was recorded on the same day at the same rate.
3. A currency revaluation was conducted on 31/01/2024, with the rate adjusted to 1 CNY = 4.30 THB.
4. The journal entry incorrectly reflected an exchange rate difference of 70, calculated as 100 x 5 - 100 x 4.30 (instead of the correct amount, 42 CNY, calculated as (100 - 40) x 5 - (100 - 40) x 4.30).

cc: @Saran440 @ps-tubtim

### CODE REVIEW

**Comment by Saran440** [comment]
@newtratip Can you add step to error this PR please?

**Comment by newtratip** [comment]
@Saran440 I add step to error in description.

**Review by kittiu — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
LFTM :+1:

**Pull request merged**
