### PR TITLE
[14.0][MIG] l10n_th_promptpay

### PR DESCRIPTION
**Pull request by poonlap**

### CODE REVIEW

**Comment by kittiu** [comment]
LGTM, no changes.

@poonlap I am not sure why Travis fail. May be can you try to force push once again?

**Review by kittiu — APPROVED** [review]

**Comment by sansirit** [comment]
I restarted the Travis job. It is passed.

**Comment by poonlap** [comment]
@kittiu  Thank you krub.

**Comment by poonlap** [comment]
> 
> 
> I restarted the Travis job. It is passed.

@sansirit 
Thank you.

**Pull request merged**
