### PR TITLE
[16.0][MIG] l10n_th_account_tax_multi

### PR DESCRIPTION
**Pull request by Saran440**
Still work in process

Depend On:
- [x] https://github.com/OCA/account-payment/pull/641
- [x] https://github.com/OCA/l10n-thailand/pull/394

### CODE REVIEW

**Comment by supichayat** [comment]
From functional test about multi deducted Withholding Tax
please following test step below,

1. Create Vendor Bill with **multi percentage of withholding tax each line** and Confirm
2. Register Payment
3. Select Payment Difference in **Mark invoice as fully paid (multi deduct)** and Create Payment
4. create WHT Certification
5. In column Base Amount, **there is none value found**.

System suppose to send base amount value from vendor bill to withholding moves.

**Comment by Saran440** [comment]
@supichayat Thank you for your review. I fixed it please recheck.

**Comment by supichayat** [comment]
From Functional test about multi deduction WHT and Included VAT, please following test step below.

1. create Vendor Bill with 2 lines as below
     1.1 Unit price 1,000 THB + Input VAT 7% (Included) + WHT PND3 1%
     1.2 Unit price 1,000 THB + Input VAT 7% (Included) + WHT PND3 5%
unknown_094
2. register payment, wizard will be shown up.
unknown_095
3. then create payment, an error occurred as attached.
unknown_096

**Comment by Saran440** [comment]
@supichayat please recheck. it error because `Deduction Amount` is field Monetary (support digit from currency) But other function calculate with wht amount is not rounding

I fixed it in module l10n_th_account_tax -> 0a4d2af914109aba3f4c92dcae1c059681096d28 by rounding wht amount 2 digits.
It will rounding by line
Selection_009

**Comment by kittiu** [comment]
@Saran440 can this merged?

**Review by kittiu — APPROVED** [review]

**Comment by Saran440** [comment]
@kittiu yes, this PR ready to merge.

**Pull request merged**
