### PR TITLE
[14.0][IMP] l10n_th_withholding_tax, Add PIT feature.

### PR DESCRIPTION
**Pull request by kittiu**
This PR do not change any logic in calculate WHT. But add a useful field "Withholding Base Amount", and as such, it is now possible to change base amount in order to calculate back the withholding tax.

image

### CODE REVIEW

**Comment by kittiu** [comment]
@Saran440 can you help review this one please.

**Comment by Saran440** [comment]
@kittiu
On wizard. Fields `Amount` + `Payment Difference` must equal `Withholding Base` always?
if yes, you should add function for check this.

**Comment by kittiu** [comment]
> @kittiu On wizard. Fields `Amount` + `Payment Difference` must equal `Withholding Base` always? if yes, you should add function for check this.

No, not necessary. It is possible that, only 1 out of 2 invoice line is the base amount. I do this intentionally.
Also, even if in invoice line, there are not WHT lines, we can still select the WHT in payment wizard and type in base amount manually.

Now, it is very flexible.

**Review by Saran440 — APPROVED** [review]
Functional Test,
Vat + WT -> :+1: 
WT only -> :+1:

**Comment by kittiu** [comment]
@Saran, as discussed,

* I moved PIT feature from https://github.com/OCA/l10n-thailand/pull/261 here.
* Except "Create Cert.", I will create another PR for `l10n_th_withholding_tax_cert`
* I will also create PR for `l10n_th_withholding_tax_multi` to make it support PIT too.

Please help review/approve this PR, and we will continue with the rest.

**Comment by kittiu** [comment]
Ready for review.

**Comment by kittiu** [comment]
@Saran440 @ps-tubtim This PR is ready for review.

**Comment by Saran440** [comment]
Functional Test

**Case: Cancel Payment with PIT**

1. Create Vendor Bills and select line with PIT > Register Payment normal process
2. View PIT on vendor (it's correct)
Selection_004
3. Cancel Payment and View PIT on vendor again
Selection_005

Should be check cancel checkbox?
and I test payment reset to draft and cancel again.
It reversed and not check cancel last line.

Selection_006

-------------------------------------------------------------------

**Case: Some field is not used**

1. Payment View
Selection_003
 
2. Vendor View
Selection_007

**Review by Saran440 — CHANGES_REQUESTED** [review]
Review above

**Comment by peerayaproud** [comment]
I would like to raise issue about employee expense
If the employee made an expense report and there is PIT.
The Odoo will record PIT data in "that employee" master data not the vendor who got paid from employee.
Also the WHT Certificate will print employee's name.
The employee is just a middle man who transfer company's money to Vendor.

Selection_119
Selection_118
Selection_120

**Comment by newtratip** [comment]
@kittiu, Could you fix the conflict files ?

**Comment by kittiu** [comment]
TODO:

- [ ] Fix the reported bugs (above)
- [ ] Make sure that, when this module works with expense and clearing (and l10n_th_expense_tax), it use correct bill_partner_id when withhold.
- [ ] (not this PR), Fix for normal Tax Invoice, currently, the module l10n_th_expense_tax invoice should also dr/cr on bill_partner_id

@Saran440

**Comment by kittiu** [comment]
> Review above

Note on the Type of Income, it is intentional to have user fill it later one (just before printing cert is ok).

**Comment by kittiu** [comment]
Closed as move to https://github.com/OCA/l10n-thailand/pull/272

**Pull request closed without merging**
