### PR TITLE
[15.0[MIG] l10n_th_gov_purchase_agreement

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard Migration.

Waiting For

- [x] https://github.com/OCA/purchase-workflow/pull/1596

### CODE REVIEW

**Comment by PatthamaCH** [comment]
@ps-tubtim pls revise the "invoice plan" tab, should be can not edit it.

**Comment by ps-tubtim** [comment]
> @ps-tubtim pls revise the "invoice plan" tab, should be can not edit it.

@PatthamaCH I already updated it. Could you review it again?

**Review by PatthamaCH — APPROVED** [review]
OK

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Comment by Saran440** [comment]
This module depend on https://github.com/OCA/l10n-thailand/pull/340

**Pull request merged**
