### PR TITLE
[13.0][FIX] Report - tax_amount

### PR DESCRIPTION
**Pull request by kongrattapong**
Issue: https://github.com/OCA/l10n-thailand/issues/96

สร้าง Invoice 2 ฉบับ
1. Tax < 0 
Selection_070

2. Tax > 0
Selection_073

เมื่อทำการ เรียกรายงาน
Selection_074

### CODE REVIEW

**Comment by kittiu** [comment]
I think this is not what we mean.

**Comment by kongrattapong** [comment]
sorry for misunderstand and not asking first, I Fixed it already.

INV
Selection_091
Selection_090


XLSX
Selection_094

PDF
Selection_093

HTML
Selection_089

**Comment by Saran440** [comment]
@kongrattapong please, using `cherry-pick` from #102 into v13

**Comment by kittiu** [comment]
> @kongrattapong please, using `cherry-pick` from #102 into v13

Thanks ok @Saran440 we are fixing it same time.

**Review by kittiu — APPROVED** [review]

**Pull request merged**
