### PR TITLE
[15.0][ADD] l10n_th_tier_department / l10n_th_tier_department_demo

### PR DESCRIPTION
**Pull request by ps-tubtim**
This module adds the following features to tier validation, aimed to follow Thai Government regulations.

1. Add an Approval Level table to Department
2. Add default tier definitions

Waiting for

- [x] https://github.com/OCA/hr-expense/pull/153

### CODE REVIEW

**Comment by Saran440** [comment]
@ps-tubtim I rename module to `l10n_th_tier_department` is base tier department
and 1 module is `l10n_th_tier_department_demo` for demo goverment only

what do you think?

**Review by Saran440 — APPROVED** [review]
Add test script and function test :+1:

**Review by supichayat — APPROVED** [review]
functional test.

**Pull request merged**
