### PR TITLE
[15.0][MIG] l10n_th_account_asset_management

### PR DESCRIPTION
**Pull request by Saran440**
Depends:
- [x] account_asset_number - https://github.com/OCA/account-financial-tools/pull/1519

### CODE REVIEW

**Comment by ps-tubtim** [comment]
@Saran440 Please separate the commits following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 and add you to CONTRIBUTORS.rst.

**Comment by Saran440** [comment]
@ps-tubtim No need to split commit because this PR is not change

**Comment by ps-tubtim** [comment]
@Saran440 Please apply this PR https://github.com/OCA/l10n-thailand/pull/334. Thank you.

**Review by ps-tubtim — APPROVED** [review]
Functional Test: OK

**Comment by TheerayutEncoder** [comment]
LGTM :+1:

**Review by TheerayutEncoder — APPROVED** [review]
LGTM :+1:

**Pull request merged**
