### PR TITLE
[12.0][ADD] account_billing

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this is not Thailand specific.

**Comment by Saran440** [comment]
Are you saying other countries use it?

**Comment by pedrobaeza** [comment]
Well, this repository is only for things specific to Thailand, and reading the description, this might be something more generic for OCA/account-invoicing.

**Comment by Saran440** [comment]
got it. Thank you for your suggestion. I will close this PR and move to OCA/account-invoicing.

**Comment by kittiu** [comment]
@pedrobaeza thank you :)

**Comment by Saran440** [comment]
move on OCA/account-invoicing

**Pull request closed without merging**
