### PR TITLE
[15.0][ADD] l10n_th_multicurrency_revaluation

### PR DESCRIPTION
**Pull request by ps-tubtim**
This module was written to extend the functionality of the accounting module to support the multicurrency and to allow you to generate automatically revaluation journal entries.

### CODE REVIEW

**Comment by Saran440** [comment]
@AnutToc module depend on operating unit should create new module like a `l10n_th_multicurrency_revaluation_operating_unit`
because we can not used OU in project

**Comment by Saran440** [comment]
Fix multi currency can revaluation 1 time / 1 currency rate

**Review by Nantikan23 — COMMENTED** [review]
Step to Test
1. Create Vendor Bill Accounting Date 14/11/23 Price 100$ Rate 30 Status Posted (BILL/2023/11/0001) 
2. Generate Currency Revaluation 30/11/23 Rate 32 (MISC/2023/11/0001 Ref. BILL/2023/11/0001)
3. Generate Reverse Currency Revaluation 1/12/23 (MISC/2023/11/0002 Ref. MISC/2023/11/0001)
4. Generate Currency Revaluation 31/12/23 Rate 35 
     **User Error** No accounting entry has been posted.

From no. 4, I think that Revaluation can be calculated because there is a vendor bill with posted status.

**Comment by Saran440** [comment]
@Nantikan23 Thank you for your review, I fixed it. Can you recheck please

**Review by Saran440 — APPROVED** [review]
Functional Test and add test script :+1:

**Review by Nantikan23 — COMMENTED** [review]
Step to test 
1. Create MISC/2023/11/0006 (Journal =  	
Miscellaneous Operations)
 Dr. 210100 Account Payable           3,000
     - Allow Currency Revaluation = True
     - Amount in Currency = 100 BUR
     - Currency Rate = 30
 Cr. 520300 Office Expenses                        3,000

2. Generate Currency Revaluation 30/11/2023  Currency Rate = 35 (MISC/2023/11/0007 Ref. MISC/2023/11/0006)
3. Generate Reverse Currency Revaluation 1/12/2023 (MISC/2023/12/0006 Ref. MISC/2023/11/0007)
4. Generate Currency Revaluation 31/12/2023  Currency Rate = 34 
Screenshot from 2023-11-23 13-56-51

**User Error** No accounting entry has been posted.

Screenshot from 2023-11-23 13-57-14

According to Article 4, the system should run a revalue again. As this document still have an outstanding balance, the system must have additional conditions for running data such as
1. The journal entry has an account code that is set to be an account code Allow Currency Revaluation = True 
2. The document has post status. 
3. The document has not yet been reconciled.
The above terms apply to all types of journals other than sales and purchases

**Review by Nantikan23 — APPROVED** [review]
Functional Test

**Pull request merged**
