### PR TITLE
[12.0][FIX]l10n_th_vat_report

### PR DESCRIPTION
**Pull request by ps-tubtim**
- fix xlsx report

### CODE REVIEW

**Comment by kittiu** [comment]
@ps-tubtim please, can you explain more what is being fixed (and what was the problem)

**Comment by ps-tubtim** [comment]
@kittiu Thank you for review. In the old code, columns in xlsx report swap sometime because dict doesn't have order. I solve by sort dict by keys for fixed its.

**Comment by kittiu** [comment]
@ps-tubtim
1) please explain like this in commit, and also in history log.
```
Columns in xlsx report swap sometime because dict doesn't have order. Resolved by sort dict by keys for fixed its.
```
2) there is still small things to fix,
```
2019-08-30 11:28:40,748 162 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (base_amount, tax_base_amount) of vat.report.view() have the same label: Base Amount.
```

**Comment by ps-tubtim** [comment]
- Fix column swap in xlsx report
- Fix wrong query database to report 
- Add test script

**Pull request merged**
