### PR TITLE
[15.0][IMP] l10n_th_gov_account_asset_management: add fields, change display name

### PR DESCRIPTION
**Pull request by ps-tubtim**
- Add new fields to enter additional information.
- Change the display name of the asset.
- Pass the asset number to the reference of the journal entry.

This PR waiting for

- [x] https://github.com/OCA/account-financial-tools/pull/1507

### CODE REVIEW

**Comment by Saran440** [comment]
Add permission for purchase user can visible and edit asset.
What do you think?

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by Saran440 — CHANGES_REQUESTED** [review]
test error

this pr depend on https://github.com/OCA/l10n-thailand/pull/360

**Review by Saran440 — APPROVED** [review]

**Review by Nantikan23 — APPROVED** [review]
Functional Tested

**Pull request merged**
