### PR TITLE
[15.0][ADD] l10n_th_account_wht_cert_form

### PR DESCRIPTION
**Pull request by kurogeek**
This module requires the following modules to work.
 
l10n_th_amount_to_text #282 
l10n_th_fonts #273 
l10n_th_account_tax #279

Reference of redesign modules #272

### CODE REVIEW

**Comment by kittiu** [comment]
@kurogeek is this PR based on this branch? https://github.com/ecosoft-odoo/l10n-thailand/tree/14.0-add-l10n_th_account_tax/l10n_th_account_wht_cert_form

From the commit history, it seem to come from branch 14.0.

As of 15.0, we just start over again, you can just copy from the above branch the l10n_th_account_wht_cert_form, and add it to 15.0 branch. OK?

Similar to https://github.com/OCA/l10n-thailand/pull/294/commits, you can see the first commit is the copy over from the above branch. Then we add 1 commit for the change from 14 -> 15 if any.

**Comment by kittiu** [comment]
So the step should be,

1. Create a new branch from current 15.0
2. Just copy over the module l10n_th_account_wht_cert_form from https://github.com/ecosoft-odoo/l10n-thailand/tree/14.0-add-l10n_th_account_tax -> this will be initial.
3. Do the migrate to v15

**Comment by kurogeek** [comment]
Ohh, I didn't see that you have this branch. Sorry, my mistake. I'll do as you suggested.

**Comment by Saran440** [comment]
@kurogeek Hello, Could you please review https://github.com/OCA/l10n-thailand/pull/305 instead of this PR? because we refactored code for v15

**Comment by kurogeek** [comment]
Yes, of course

**Pull request closed without merging**
