### PR TITLE
[14.0][ADD] l10n_th_account_asset_management

### PR DESCRIPTION
**Pull request by ps-tubtim**
This module adds images and chatter to the assets.
This module updates the financial assets report for Thailand.

Waiting for

- [x] https://github.com/OCA/account-financial-tools/pull/1213
- [x] https://github.com/OCA/account-financial-tools/pull/1238

Progress:

- [ ] Test

### CODE REVIEW

**Comment by kittiu** [comment]
@ps-tubtim are you still working on this?

**Comment by ps-tubtim** [comment]
> @ps-tubtim are you still working on this?

@kittiu Sorry for the late reply. I still working on this.

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
