### PR TITLE
[15.0][MIG/REF] l10n_th_account_tax_multi

### PR DESCRIPTION
**Pull request by Saran440**
from https://github.com/OCA/l10n-thailand/pull/283

Standard migration, ready for review

Depends:

 - [x] l10n_th_account_tax https://github.com/OCA/l10n-thailand/pull/294
 - [x] account_payment_multi_deduction https://github.com/OCA/account-payment/pull/561

This module `l10n_th_account_tax_multi` is the replacement of, `l10n_th_withholding_tax_multi` of v13

### CODE REVIEW

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Review by supichayat — APPROVED** [review]
funtional tested

**Comment by Saran440** [comment]
This module depend on PR https://github.com/OCA/l10n-thailand/pull/364

**Pull request merged**
