### PR TITLE
[14.0][MIG] l10n_th_partner

### PR DESCRIPTION
**Pull request by kittiu**
Dependencies

- [X] partner_company_type https://github.com/OCA/partner-contact/pull/998
- [X] partner_firstname https://github.com/OCA/partner-contact/pull/981

### CODE REVIEW

**Comment by sbidoul** [comment]
@kittiu The dotfiles on the 14.0 branches for this repo were outdated, hence the travail failure.
What I don't understand, though, is why travis did not report the error. Can you rebase to pick-up the latest dotfiles I pushed on the main branch, and retry the merge ?

**Comment by kittiu** [comment]
OK Stephane. Thank you I will try.

**Comment by kittiu** [comment]
Rebsed.

**Pull request merged**
