### PR TITLE
[16.0][MIG] l10n_th_account_tax_report

### PR DESCRIPTION
**Pull request by Saran440**
Cherry-pick from https://github.com/OCA/l10n-thailand/pull/399

- Reformat code
- Delete JS

TODO:
- [x] text has long more than 1 line. new line is over height new line

Depend On:
- [x] https://github.com/OCA/l10n-thailand/pull/394
- [x] https://github.com/OCA/l10n-thailand/pull/390

### CODE REVIEW

**Comment by supichayat** [comment]
From test about printing Withholding Tax Report 
When vendor's address has many characters, there is an error found as attached below, 

unknown_087

**Comment by Saran440** [comment]
@supichayat Thank you for your review. I fixed it please recheck.

**Comment by supichayat** [comment]
From testing about report late case, please following test step below.

1. Create tax invoice with Report Late as attached (Report month is November)
Screenshot from 2023-11-09 00-00-16
2. Go to Reporting Menu and Generate the Thai tax report during December period (01-31/12/23).
The created report will include 2 items in 1., Even though the report date is 30/11/23 since it will pull all report late data before the selected month to show up.
Screenshot from 2023-11-09 00-08-32
3. In my opinion, I think the system suppose to **pull only the report date in the selected month not including all report late data before.** (in this case, the report should present 2 items above if the selected period was November.)

**Comment by Saran440** [comment]
@supichayat Fixed it. Can you test again please. cherry-pick from https://github.com/OCA/l10n-thailand/pull/412

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
