### PR TITLE
[FIX] function get_and_parse_csv required 1 attributes

### PR DESCRIPTION
**Pull request by Saran440**
Error when import.
base on this module (base_location_geonames_import) has change function get_and_parse_csv to request 1 attribute
- add attribute in function get_and_parse_csv

TO DO
- [x] Test Script

NEXT PR
- Add New menu Sub-district and Sub-district Code

Thailand have standard industry code province, district, Sub-district
reference : http://www.ratchakitcha.soc.go.th/DATA/PDF/2549/D/062/32.PDF

cc : @ps-tubtim @kittiu

### CODE REVIEW

**Review by kittiu — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Comment by Saran440** [comment]
@kittiu could you merge this PR please? and https://github.com/OCA/l10n-thailand/pull/146 ready to review and merge

**Comment by kittiu** [comment]
@Saran440 can you check.
https://travis-ci.org/github/OCA/l10n-thailand/jobs/705723377#L905

**Comment by Saran440** [comment]
@kittiu I think I fix it on https://github.com/OCA/l10n-thailand/pull/146. May be I should be close this PR

**Comment by Saran440** [comment]
move on #146

**Pull request closed without merging**
