### PR TITLE
[15.0][MIG] l10n_th_fonts: Migration to 15.0

### PR DESCRIPTION
**Pull request by amincheloh**

### CODE REVIEW

**Comment by kittiu** [comment]
Thank you @amincheloh for your contribution.

ping @Saran440 can you help test this?

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:  LGTM

**Comment by kittiu** [comment]
@amincheloh thanks for contributing the 1st module for v15. Hope there are more. :)

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
@amincheloh I think there was some update (from OCA team) regarding pre-commit in the 15.0 repo on Nov 11. I am not sure if this is done.
But you can try rebase your code on the new one, run pre-commit and push again. Thanks.

**Comment by amincheloh** [comment]
@kittiu rebased

**Pull request merged**
