### PR TITLE
[15.0][MIG/RFC] l10n_th_account_wht_cert_form

### PR DESCRIPTION
**Pull request by Saran440**
- Change name `l10n_th_withholding_tax_cert_form` to `l10n_th_account_wht_cert_form`
- Refactored Code
- Change `t-esc` to `t-out` from https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#tasks-to-do-in-the-migration

### CODE REVIEW

**Comment by Saran440** [comment]
waiting pr https://github.com/OCA/l10n-thailand/pull/308 merge

**Review by ps-tubtim — APPROVED** [review]
LGTM.

**Review by supichayat — APPROVED** [review]
funtional tested

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Pull request merged**
