### PR TITLE
[13.0][FIX] l10n_th_tax_invoice, error reconcile invoice/refund with undue vat

### PR DESCRIPTION
**Pull request by kittiu**
- Create vendor bill with undue vat
- Create refund with unde vat
- Try to pay by refund
- Error that tax invoice number is not filled

This is because Odoo create cash basis entry in the way we don't expect

### CODE REVIEW

**Comment by kittiu** [comment]
cc @Saran440 @ps-tubtim @newtratip

**Review by Saran440 — APPROVED** [review]
code reviewed. LGTM :+1:

**Review by ps-tubtim — APPROVED** [review]
LGTM.

**Pull request merged**
