### PR TITLE
[15.0][MIG] l10n_th_sequence_refactored

### PR DESCRIPTION
**Pull request by Saran440**
Standard Migration

### CODE REVIEW

**Comment by Saran440** [comment]
@sansirit I think we should merge `l10n_th_sequence_preview` into `l10n_th_sequence_refactored`
because it small add feature.

WDYT?

**Review by TheerayutEncoder — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]
Code Review: LGTM.

**Pull request merged**
