### PR TITLE
[13.0][IMP] l10n_th_partner

### PR DESCRIPTION
**Pull request by ps-tubtim**
Issue: https://github.com/OCA/l10n-thailand/issues/83

Example about person
partner_person

Example about company
partner_company

### CODE REVIEW

**Comment by kittiu** [comment]
Perfect!
Just add the DESCRIPTION, you can explain that we have 2 types, contact and company.
@poonlap @kiattipong, can you review and click approve?
2 approved, I can merge.

**Review by kittiu — APPROVED** [review]

**Comment by ps-tubtim** [comment]
@kittiu Thank you for review. I added some description.

**Comment by kittiu** [comment]
@Saran440 please review/approve this. Then I will merge. Thanks!

**Review by Saran440 — APPROVED** [review]
Functional Test. LGTM :+1:

**Pull request merged**
