### PR TITLE
[16.0][MIG] l10n_th_account_tax

### PR DESCRIPTION
**Pull request by Saran440**
Cherry-pick https://github.com/OCA/l10n-thailand/pull/396

- Fix function `_prepare_deduction_list` for other module can hook partner instead of add it in function
- Add test script manual_tax and else for cover case
- Remove tab `Tax Cash Basis Moves` in move
- Add `Paid Continuously` on WHT
- Cherry-pick from https://github.com/OCA/l10n-thailand/pull/413

### CODE REVIEW

**Review by supichayat — COMMENTED** [review]
From functional tested about **Full Refund Credit note** for Vendor Bill, There is an error occured per attached file
image
please following test step below
1) create vendor bill from PO with Input VAT 7% (excluded or included)
2) click **credit note** button
3) select credit method as **Full Refund** or **Full refund and new draft invoice**
4) **User Error** will be shown up to require Tax Invoice and Tax Date

In my opinion, system suppose to have field for users to fill in those information in this step.

**Comment by supichayat** [comment]
From functional test about **credit note on Undue Input VAT and Undue Output VAT**
please following test step below

**Vendor Bill**
1. create vendor bill with **Undue Input VAT 7% (excluded or included)**
2. Add **credit note** 
3. Register Payment and **Clear Tax** for credit note
4. Cash Basis Entries will be created, Tax base and Tax amount are **positive** value.

**Customer Invoice**
1. create customer invoice with **Undue Output VAT 7% (excluded or included)**
2. Add **credit note** 
3. Register Payment for credit note
4. Cash Basis Entries will be created, Tax base and Tax amount are **positive** value.

However, Tax base and Tax amount in tab Tax Invoice on credit note suppose to be **negative** value.

**Comment by Saran440** [comment]
@supichayat I fixed it. Thank you for your review. Please recheck again.

**Review by supichayat — APPROVED** [review]
functional tested

**Review by TheerayutEncoder — APPROVED** [review]
Thanks @supichayat for test detail
Functional Tested :+1:

**Comment by supichayat** [comment]
About credit note function, I found some errors from testing step as below.

1.  Create Vendor Bill
2.  Added credit note, select credit method as **Partial Refund** and fill in Tax Invoice number and Tax invoice Date field
3.  then click Reverse
4.  Vendor Credit Note will be created, go to Tax Invoice tab
5.  **tax invoice number and date didn't be sent** from filled data in the created credit note wizard as expected.

When testing by selected Full Refund method, the data was sent to Tax Invoice tab as usual. So this supposed to be for Partial Refund as well.

**Comment by supichayat** [comment]
About credit note function, I found some errors from testing step as below.

1. Create Vendor Bill with Input VAT 7% and confirm it
2. Duplicate this Vendor Bill
3. Change Input VAT 7% to Undue Input VAT 7%
4. Click Confirm
5. The user error will be shown up due to the tab tax invoice still existed from the duplicated vendor bill.
Screenshot from 2023-10-27 17-51-00

However, when change tax to Undue Input VAT the tab tax invoice suppose to not existed as usual.

**Comment by Saran440** [comment]
@supichayat Fixed it for 2 comment. please recheck.

**Comment by supichayat** [comment]
IMHO, I think wording on Customer Tax Invoice Number setting might be a bit hard to understand clearly for users.
and I have some suggestions for wording to be more clear as below,
1) For description, you can adjust to "In case of Sales Undue VAT, Define your tax invoice number which is created after payment when user didn't setup Tax Invoice Sequence in Tax setting"
2) Payment Document Number
3) Invoice Document Number
Screenshot from 2023-11-27 10-54-00

Please kindly consider it, Thank you.

**Comment by Saran440** [comment]
@supichayat I change wording following image and description. please recheck.
Selection_015

**Comment by Saran440** [comment]
I add config zero vat on menu Taxes.
it will create Tax Invoices only (no create move line same as core odoo) when you checked option zero vat
Selection_016

**Pull request merged**
