### PR TITLE
[15.0][MIG] l10n_th_amount_to_text

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration, ready for review

### CODE REVIEW

**Comment by kittiu** [comment]
@sang-sakarin ok, I think I found the problem. We need to make sure that it is the same in requirement.txt and manifest file.
If you tested it ok, please help approve this one. Normally, we need 2 approves to merge the PR.

**Comment by kittiu** [comment]
Note: also, you can always find existing PR first, sometime the migration is under way for your needed module. Thanks to making contribution.

**Comment by kittiu** [comment]
@Saran440 @ps-tubtim can you review this.

**Review by Saran440 — APPROVED** [review]
No major change :+1:

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
