### PR TITLE
[14.0][MIG] l10n_th_tax_invoice_kittiu

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration, ready for review.

### CODE REVIEW

**Comment by Cncd10** [comment]
Functional Test @kittiu 
I found an error in step Create payment.
Step Test
         1. Create PO --> field Taxes Select "Undue Input Vat 7%"
         2. Create Bill --> Confirm
         3. Register Payment --> **I found Odoo error**
Error:
Odoo Server Error
Selection_165

**Comment by kittiu** [comment]
@Cncd10 can you show me your Undue Tax configuration?
Note: I can't replicate the error on my machine yet.

**Comment by kittiu** [comment]
Here is what I did and it works fine.

1. New data base with Demo data, and no country selected (so it will use demo CoA).
2. Install module invoicing
3. Instal lmodule `l10n_th_tax_invoice` v14
4. Setup Undue Tax 15%
5. Create a product "Service" with Control Policy = On ordered quantities
6. Execute flow PO -> INV -> PAY as normal.

image

Here is the documents

image

image

**Comment by Cncd10** [comment]
@kittiu 
I tried test again as you suggested. I can't fine any error.
may be i setting something wrong.

**Comment by kittiu** [comment]
cc @Saran440 @ps-tubtim @newtratip

**Comment by Saran440** [comment]
Functional Test
Selection_004

Step to error
1. Create new database with demo (without Country)
2. Install purchase, inventory, invoice and l10n_th_tax_invoice
3. Config cash basis
Selection_005
4. Go to Taxes and duplicate tax from purchase and config.
Selection_006
Selection_007
5. Create bills (direct or PO) > register payment > Create payment > it throw error.
Peek 2020-11-14 17-28

Note: if not install module l10n_th_tax_invoice, it not error

**Comment by kittiu** [comment]
@Saran440 thanks for your review.
Fixed.

**Comment by kittiu** [comment]
Manual merge due to Travis problem.

**Pull request merged**
