### PR TITLE
[15.0][ENH] l10n_th_partner: check duplicate vat and branch

### PR DESCRIPTION
**Pull request by ps-tubtim**
Show error when duplicate Tax ID and Tax Branch

Selection_094

### CODE REVIEW

**Review by Saran440 — COMMENTED** [review]
if we have child of partner (same as vat and branch). Is it work?

**Comment by ps-tubtim** [comment]
> if we have child of partner (same as vat and branch). Is it work?

@Saran440 I think it covers case parent-child because it checks when a partner has VAT and branch.

**Review by Nantikan23 — APPROVED** [review]
Functional Tested

**Review by Saran440 — APPROVED** [review]
OK :+1:

**Pull request merged**
