### PR TITLE
[15.0][ENH] l10n_th_gov_purchase_request: allow committee is not an employee

### PR DESCRIPTION
**Pull request by ps-tubtim**
- Show column `Committee Name`
- Compute `Committee Name` from `Employee`

Selection_258

### CODE REVIEW

**Comment by Saran440** [comment]
@ps-tubtim Please fix conflict file

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Comment by Saran440** [comment]
@Nantikan23 @supichayat please review this PR.

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Review by supichayat — APPROVED** [review]
functional tested by added committee who is not employee in the committee name column and then request validation with no error.

**Pull request closed without merging**
