### PR TITLE
[15.0][MIG/REF] l10n_th_account_tax_report

### PR DESCRIPTION
**Pull request by Saran440**
From: https://github.com/OCA/l10n-thailand/pull/281

Due to too much fragmentation which make it very difficult to develop. From version 14, we decide to include multiple related addons into single addon.

This `l10n_th_account_tax_report` are from v14's,
- l10n_th_tax_report
- l10n_th_withholding_tax_report

NOTE: This PR has change view menu reporting and it will affect with `l10n_th_account_tax`

Depend on:
- [x] https://github.com/OCA/l10n-thailand/pull/339

### CODE REVIEW

**Review by supichayat — COMMENTED** [review]
V.15 ยังขาด Tax report format ของ RV ค่ะ
Screenshot from 2023-02-08 15-36-57

**Comment by Saran440** [comment]
[FIX]  result should get data late report tax is not correct

Test Case:
Filter Date From 2023-01-15 to 2023-02-10
- [x] Report Date 2023-02-05, result should output
- [x] Report Date 2023-01-31, result should output
- [x] Report Date 2023-01-14, result shouldn't output
- [x] Report Date 2023-02-11, result shouldn't output
- [x] Report Date 2024-02-01, result shouldn't output
- [x] Report Date 2022-12-01 Late report 1 month, result should output
- [x] Report Date 2022-12-01 Late report 2 month, result should output

**Comment by Saran440** [comment]
@supichayat Fixed, Thank you for your feedback, Can you check it again please?

**Review by Nantikan23 — APPROVED** [review]
Functional tested

**Comment by supichayat** [comment]
Functional tested

**Review by supichayat — APPROVED** [review]
Functional tested

**Pull request merged**
