### PR TITLE
[13.0][MIG] l10n_th_withholding_tax_cert_form

### PR DESCRIPTION
**Pull request by kongrattapong**
This module depends on [l10n_th_withholding_tax_cert](https://github.com/OCA/l10n-thailand/tree/13.0/l10n_th_withholding_tax_cert).

### CODE REVIEW

**Comment by kittiu** [comment]
Please also state in the description of this PR that, this module depends on other one. You can use like this,
Depends on,
- [ ] xxx PR number, etc.

**Comment by kittiu** [comment]
I don't have the background image of WHT cert. Do you?
image

**Comment by kongrattapong** [comment]
> I don't have the background image of WHT cert. Do you?
> image

@kittiu I Have the background but I'll check it again.

Selection_074

**Comment by kongrattapong** [comment]
> Please also state in the description of this PR that, this module depends on other one. You can use like this,
> Depends on,
> 
> * [ ]  xxx PR number, etc.

thank for review.

**Comment by kittiu** [comment]
Now you can rebase. We can see if it pass test.

**Pull request merged**
